weasel_words <- c(
  "and/or",
  "are a number",
  "clearly",
  "completely",
  "exceedingly",
  "excellent",
  "extremely",
  "fairly",
  "few",
  "huge",
  "hypothesize",
  "interestingly",
  "intra",
  "is a number",
  "largely",
  "many",
  "mostly",
  "quite",
  "relatively",
  "remarkably",
  "respectively",
  "several",
  "significantly",
  "substantially",
  "surprisingly",
  "the process of",
  "tiny",
  "various",
  "vast",
  "very",
  "via"
  )

devtools::use_data(weasel_words, overwrite = TRUE)
